import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import Heading from '@/components/common-ui/heading/heading';
import Layout from '@/components/layout/layout';
import TicketListToolbar from '@/components/tickets/ticket-list/ticket-list-toolbar/ticket-list-toolbar';
import TicketList from '@/components/tickets/ticket-list/ticket-list/ticket-list';
import SingleTicketHeader from '@/components/tickets/single-ticket/single-ticket-header/single-ticket-header';

export default function Home() {
	return (
		<>
			<Head>
				<title>AI Helpdesk</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<>
				<Layout>
					<Heading />
					<TicketListToolbar />
					<TicketList />
				</Layout>
			</>
		</>
	);
}
