import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import Layout from '@/components/layout/layout';
import TicketList from '@/components/ticket-list/ticket-list';

export default function Home() {
	return (
		<>
			<Head>
				<title>AI Helpdesk</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<TicketList />
			</Layout>
		</>
	);
}
